camera:
  annotate_background: green
  awb_mode: auto
  capture_format: png
  video_format: h264
  exposure_mode: auto
  photo_effect: solarize
  resolution: (4056, 3040)
  splitter_port3_resize: (640, 480)
  splitter_port3_format: h264
  speaker_volume: 60
  meter_mode: average
  horizontal_flip: False
  vertical_flip: False
  tl_photo_intvl_in_seconds: 5
  tl_playback_in_hundreth_s: 4
  stopmotion_playback_fps: 10
  iso: 0  # zero is auto
  rotation: 0
  saturation: 0
  sharpness: 0
  shutter_speed: 0  # zero is auto
  video_denoise: True
  video_stabilization: False
  zoom_speech: False
  menu_speech: False
  value_speech: False
pi_cam_app:
  ip: 0.0.0.0
  port: 8099
  gui: False
stream:
  ip: 0.0.0.0
  port: 9090
  format: h264
  resize: (640, 480)
  splitter_port: 0
memory_stream:
  format: mjpeg
  quality: 23
  splitter_port: 1
