camera:
  annotate_background: green
  awb_mode: auto
  capture_format: png
  exposure_mode: auto
  horizontal_flip: false
  iso: 0
  menu_speech: true
  meter_mode: average
  photo_effect: none
  resolution: (4056, 3040)
  rotation: 0
  saturation: 0
  sharpness: 0
  shutter_speed: 0
  speaker_volume: 60
  splitter_port3_format: h264
  splitter_port3_resize: (640, 480)
  stopmotion_playback_fps: 10
  streaming: false
  tl_photo_intvl_in_seconds: 5
  tl_playback_in_hundreth_s: 4
  value_speech: true
  vertical_flip: false
  video_denoise: true
  video_format: h264
  video_stabilization: false
  zoom_speech: false
memory_stream:
  format: mjpeg
  quality: 23
  splitter_port: 1
pi_cam_app:
  gui: false
  ip: 0.0.0.0
  port: 8099
stream:
  format: h264
  ip: 0.0.0.0
  port: 9090
  resize: (640, 480)
  splitter_port: 0
