camera:
  annotate_background: green
  awb_mode: auto
  capture_format: png
  exposure_mode: auto
  photo_effect: solarize
  resolution: (1332, 990)
  speaker_volume: 60
  meter_mode: average
  horizontal_flip: False
  vertical_flip: False
  iso_mode: 0  # zero is auto
  rotation: 0
  saturation: 0
  sharpness: 0
  shutter_speed: 0  # zero is auto
  video_denoise: True
  video_stabilization: False
pi_cam_app:
  ip: 0.0.0.0
  port: 8099
