#!/usr/bin/python

import time
import board
from digitalio import DigitalInOut, Direction, Pull
import subprocess
import os
import signal
from picamera import PiCamera

camera = None
BUTTON_PIN = board.D17
JOYDOWN_PIN = board.D27
JOYLEFT_PIN = board.D22
JOYUP_PIN = board.D23
JOYRIGHT_PIN = board.D24
JOYSELECT_PIN = board.D16

buttons = [BUTTON_PIN, JOYUP_PIN, JOYDOWN_PIN,
           JOYLEFT_PIN, JOYRIGHT_PIN, JOYSELECT_PIN]
for i,pin in enumerate(buttons):
  buttons[i] = DigitalInOut(pin)
  buttons[i].direction = Direction.INPUT
  buttons[i].pull = Pull.UP
button, joyup, joydown, joyleft, joyright, joyselect = buttons

while True:
  p = None
  if not button.value:
    print("Button pressed")
    if camera:
      camera.stop_preview()
      camera = None
    p = subprocess.Popen("/home/pi/tf_obj_recognition")
    time.sleep(0.35)
  if not joyup.value:
    print("Joystick up")
    os.system("sudo shutdown -h now")
    time.sleep(0.35)
  if not joydown.value:
    print("Joystick down")
    # os.system("sudo systemctl stop tf_obj_recognition")
    if p:
      p.terminate()
    time.sleep(0.35)
  if not joyleft.value:
    print("Joystick left")
    if not camera:
      camera = PiCamera()
      camera.start_preview()
    else:
      camera.stop_preview()
      camera = None
    time.sleep(0.35)
  if not joyright.value:
    print("Joystick right")
    time.sleep(0.35)
  if not joyselect.value:
    print("Joystick select")
    os.system("sudo reboot now")
    time.sleep(0.35)

  time.sleep(0.01)
